### ISSUE TITLE
Approve Kanban board

### ISSUE THREAD

**Issue by ReemMohamedAbdelfatah** [ReemMohamedAbdelfatah/Space-Travelers-Hub#21]
Hello Microverse👋, 

We are two team members me and @Fahim-Khan-P.

This is the link to our project for the Kanban board (https://github.com/users/ReemMohamedAbdelfatah/projects/3/views/1)

have a good day!

**Comment by prolajumokeoni** [comment]
Hi @Team

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted an issue, that does not have a link to the GitHub project(kanban board)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ReemMohamedAbdelfatah** [comment]
Thank you @prolajumokeoni  I updated the link.

**Comment by KayLemba** [comment]
Hi @TEAM  👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️

Required Changes ♻️
Check the comments under the review in the inline comments.
 

- [ ] For a team with two people - check if all cards with the Team3 prefix on the template were removed from students' copy of the template. Number of cards in Backlog should be equal to 17. But your cards in your Backlog equal 13 it would be nice if you corrected this.

Please use this [template](https://github.com/microverseinc/curriculum-react-redux/projects/1)
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by algerina** [comment]
Hi beautiful team ,

Good job so far! 

May I highlight the following:

- The cards are distributed equaly.:heavy_check_mark:
- You implemented the changes required by the previous TSE:heavy_check_mark:




## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:

Your Kanban board is complete!  You are ready to start working on your project :shipit:

<img src="https://media1.giphy.com/media/10UeedrT5MIfPG/giphy.gif"/>

 
 ## Optional suggestions

- [ Optional] There's an issue with the desktop navbar,  I recommend delete the `position: fixed` 

- [ Optional]  I recommend adding a margin to you form inputs, it will look perfect.

 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

**Comment by ReemMohamedAbdelfatah** [comment]
Hello @algerina thank you for your review!
